version: "3.8"
services:
  web:
    build: ./app
    image: 471563968363.dkr.ecr.us-east-2.amazonaws.com/workshop2:workshop2_web
    command: gunicorn nc_tutorials.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
      - static_volume:/usr/src/app/static
    expose:
      - 8000
    environment:
      - DB_NAME=nc_tutuorials_db
      - DB_USER=postgres
      - DB_PASSWORD=admin123
      - DB_HOST=nctutorials.cb2hc6cg7wp4.us-east-2.rds.amazonaws.com
      - DB_PORT=5432
      - DATABASE=postgres
      - VIRTUAL_HOST=ec2-18-119-83-145.us-east-2.compute.amazonaws.com
      - VIRTUAL_PORT=8000
  nginx:
    build: ./nginx
    image: 471563968363.dkr.ecr.us-east-2.amazonaws.com/workshop2:workshop2_nginx
    volumes:
      - static_volume:/usr/src/app/static
    ports:
      - 8000:80
    depends_on:
      - web
volumes:
  static_volume:
